### ISSUE TITLE
main thread cannot pass in array

### ISSUE THREAD

**Issue by bugzpodder** [WebReflection/coincident#21] opened 2023-09-10 22:03 UTC
in the main thread I have:

`Xworker.sync.results = ['a', 'b', 'c']`
and it doesn't seem like python can access this.  Had to do:
`Xworker.sync.getResults = () => ['a', 'b', 'c']`

is there a way to get all the keys of xworker.sync on the python side?  the reason i am passing in this array from js is that I want to get a list of keys from xworker.sync in python.  I tried things like values()/entries() etc none worked.

**Comment by WebReflection** [comment] 2023-09-11 08:24
This feels like a duplicate of this https://github.com/WebReflection/coincident/issues/20#issuecomment-1713403504

**Closed by WebReflection** 2023-09-11 08:24 UTC

**Comment by WebReflection** [comment] 2023-09-11 08:27
To be more explicit, any Python related bug in here will be closed as this module is not about Python. This module is used by *polyscript* and *polyscript* has its own rules and features. If you think something doesn't work with foreign programming languages please always file a bug in *polyscript*, not here, as here Python **doesn't exist** in the first place as the goal of this project is to enable Atomics via Proxies.
